name: custom_search_bar
description: Experience total control over both the search bar and app bar UI.
version: 0.0.4
homepage: https://github.com/safvan-husain/custom_search_bar.git

environment:
  sdk: ^3.3.0
  flutter:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
